stages:
  prepare_data:
    cmd: python prepare_data.py
    deps:
      - prepare_data.py
    outs:
      - data/gig_pricing.csv

  train_model:
    cmd: python train.py
    deps:
      - train.py
      - data/gig_pricing.csv
    # Note: We aren't defining 'outs' here yet because MLflow handles our model artifacts.
    # In a stricter DVC setup, we would output a 'model.pkl' here too.